gh: patchwork: retry if the patch is not there yet
Patches can take a bit of time to appear on Patchwork, best to retry for
a bit of time before abording.

Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>

diff --git a/.github/workflows/notif.yml b/.github/workflows/notif.yml
--- a/.github/workflows/notif.yml
+++ b/.github/workflows/notif.yml
@@ -334,8 +334,14 @@ jobs:
       - name: set patchwork check
         if: startsWith(steps.tag.outputs.tag, 'patchew/')
         run: |
-          CHECK_URL="$(curl "${URL}" | jq -r 'last(.[].checks)')"
-          echo "Found: ${CHECK_URL}"
+          set_url() {
+            CHECK_URL="$(curl "${URL}" | jq -r 'last(.[].checks)')"
+            if [ -z "${CHECK_URL}" ] || [ "${CHECK_URL}" = "null" ]; then
+              echo "URL not found: '${CHECK_URL}' '${URL}'"
+              unset CHECK_URL
+              return 1
+            fi
+          }
 
           # $1: title, $2: status, $3: url
           submit() {
@@ -355,6 +361,16 @@ jobs:
               -F "description=${2}" \
               "${CHECK_URL}" | jq '.'
           }
+
+          for i in $(seq 30); do # patches can take a bit of time to appear
+            set_url && break
+            sleep 1m
+          done
+
+          if [ -z "${CHECK_URL}" ]; then
+            exit 1
+          fi
+          echo "Found: ${CHECK_URL}"
 
           submit "${{ steps.cirrus.outputs.ccl_title_0 }}" "${{ steps.cirrus.outputs.ccl_status_0 }}" "${{ steps.cirrus.outputs.url_0 }}"
           submit "${{ steps.cirrus.outputs.ccl_title_1 }}" "${{ steps.cirrus.outputs.ccl_status_1 }}" "${{ steps.cirrus.outputs.url_1 }}"
